apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  namespace: test-2
  name: basic
spec:
  tracing:
    sampling: 10000
    type: Jaeger
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true

